### ISSUE TITLE
Invoke-PowerBIRestMethod fails with Service Principal

### ISSUE THREAD

**Issue by Saltzmea** [Microsoft/powerbi-powershell#108]
Invoke-PowerBIRestMethod does not function when being called from a Service Principal. I have configured the service principal in the Azure tenant with the required API permissions, but the service account can't call the Invoke-PowerBIRestMethod. The value returned says it's not authorized even though it has permissions. I also tried this with Get-PowerBIReport -Scope Organization and Invoke-RestMethod with no success.

Example script:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$tenantId = "#####" 
$AppId = "#####" 
$PasswordClearText = "######"

$PW = ConvertTo-SecureString -String $PasswordClearText -AsPlainText -Force
$Credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $AppId, $PW

Import-Module -name MicrosoftPowerBIMgmt

$Account = Connect-PowerBIServiceAccount -Credential $Credential -Tenant $tenantId -ServicePrincipal
if(!$Account) {
    Throw "Could not connect to Power BI service account."
}

$Reportsresponse = Invoke-PowerBIRestMethod -Url 'reports' -Method Get 
if(!$Reportsresponse){
    Resolve-PowerBIError
}

$Reportsresponse.value | Out-Host

Disconnect-PowerBIServiceAccount

Message        : Response status code does not indicate success: 401 (Unauthorized).
StackTrace     :    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                    at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.<InvokeRestMethod>d__31.MoveNext()
Exception      : System.Net.Http.HttpRequestException
InvocationInfo : {Invoke-PowerBIRestMethod}
Line           : $Reportsresponse = Invoke-PowerBIRestMethod -Url 'reports' -Method Get

Position       :  - Doc\PowerShell\Azure Authentication Test - Az.ps1:46 char:20
                 + ... Reportsresponse = Invoke-PowerBIRestMethod -Url 'reports' -Method Get
                 +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

**Comment by deepundneni** [comment]
Is there any update here.. I`ve used "Invoke-PowerBIRestMethod" and "New-PowerBIReport" to publish a dashboard using Sp but i keep getting Unauthorized.

**Comment by richardlhughes** [comment]
I am experiencing the same behavior, trying to pull tenant data out from the administration rest api's. What is the preferred authorization?

**Comment by deepundneni** [comment]
I was  able to do this by using **Get-PowerBIAccessToken**

**Comment by deepundneni** [comment]
$secpasswd = ConvertTo-SecureString "xxxxxxxxxxxxxxxxxx" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("<service principal_Id/app_id>", $secpasswd)
Connect-PowerBIServiceAccount -ServicePrincipal -Credential $mycreds -Tenant $tenantId
$auth_token= Get-PowerBIAccessToken -AsString

**Comment by selopez** [comment]
Same here trying to deploy a PBI Pipeline

```
Connect-PowerBIServiceAccount -Tenant $tenantid -ServicePrincipal -Credential $Cred

$body = @{ 
    sourceStageOrder = 0 # The order of the source stage. Development (0), Test (1).   
    datasets = @(
        @{sourceId = "yyyyyyy" }
    )      
    reports = @(
        @{sourceId = "xxxxxxxx" }
    )
    options = @{
        # Allows creating new item if needed on the Test stage workspace
        allowCreateArtifact = $TRUE
        # Allows overwriting existing item if needed on the Test stage workspace
        allowOverwriteArtifact = $TRUE
    }
} | ConvertTo-Json

$url = "pipelines/{0}/Deploy" -f $pipelineId
Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
```

--------------------------------------------

- [x] Service principal with workspace permissions & Pipeline Access

- [x] Service principal with API Permissions: 
![image](https://user-images.githubusercontent.com/87112931/193833100-013319a7-d852-49ea-9cc0-3b14a94c1e23.png)

- [x] Allowed SPN to use PBI APIs
![image](https://user-images.githubusercontent.com/87112931/193833456-639c6655-533d-45a0-b766-aa35f3d1b67b.png)

**But I still getting the following response:**
```
99
{"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
0
```

**Comment by selopez** [comment]
> Same here trying to deploy a PBI Pipeline
> 
> ```
> Connect-PowerBIServiceAccount -Tenant $tenantid -ServicePrincipal -Credential $Cred
> 
> $body = @{ 
>     sourceStageOrder = 0 # The order of the source stage. Development (0), Test (1).   
>     datasets = @(
>         @{sourceId = "yyyyyyy" }
>     )      
>     reports = @(
>         @{sourceId = "xxxxxxxx" }
>     )
>     options = @{
>         # Allows creating new item if needed on the Test stage workspace
>         allowCreateArtifact = $TRUE
>         # Allows overwriting existing item if needed on the Test stage workspace
>         allowOverwriteArtifact = $TRUE
>     }
> } | ConvertTo-Json
> 
> $url = "pipelines/{0}/Deploy" -f $pipelineId
> Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
> ```
> 
> * [x]  Allowed SPN to use PBI APIs
>   ![image](https://user-images.githubusercontent.com/87112931/193833456-639c6655-533d-45a0-b766-aa35f3d1b67b.png)
> * [x]  Service principal with workspace permissions & Pipeline Access
> * [x]  Service principal with API Permissions:
>   ![image](https://user-images.githubusercontent.com/87112931/193833100-013319a7-d852-49ea-9cc0-3b14a94c1e23.png)
> 
> **But I still getting the following response:**
> 
> ```
> 99
> {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
> 0
> ```

I solved it with that changes:

- I added to the API Permissions of service principal (second pict) this: Gateway.Read.All
- And I allow another check into the PowerBI Admin portal (first pict), Dataset Execute Queries REST API

The changes need some time to work it fine...

**Comment by leblocks** [comment]
AFAIK, service principal must not have any scopes defined. Access in such cases is being controlled purely by tenant settings.
