### ISSUE TITLE
New-PowerBIWorkspace Command returns error

### ISSUE THREAD

**Issue by janelhunt** [Microsoft/powerbi-powershell#126]
Hi

A resolution to problem described below would be extremely useful as this may explain why I am currently unable to utilise the [CopyWorkspaceSampleScript](https://github.com/Microsoft/powerbi-powershell/edit/master/examples/) to duplicate workspaces - as detailed in Kay Unroth's recent [blog ](https://powerbi.microsoft.com/en-us/blog/duplicating-workspaces-by-using-power-bi-cmdlets/).  

I am a Power BI Admin and can create workspaces in the Power BI Service on my tenant where App Workspaces are now the default Workspace mode.

I have installed the latest version of the MicrosoftPowerBIMgmt module (1.0.487)

However, on issuing the command **_New-PowerBIWorkspace -Name "New WS"_**

It returns an Internal Server Error as follows:

New-PowerBIWorkspace : Operation returned an invalid status code 'InternalServerError'
At line:1 char:1
+ New-PowerBIWorkspace -Name "New WS"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:NewPowerBIWorkspace) [New-PowerBIWorkspace], HttpOperationException
    + FullyQualifiedErrorId : Operation returned an invalid status code 'InternalServerError',Microsoft.PowerBI.Commands.Workspaces.NewPowerBIWorkspace

On issuing the Powershell command Resolve-PowerBIError -Last, it returns:

RequestId        : 4d767ec8-fe7c-41e1-8d18-0355045ceb5a
Response         : Internal Server Error (500): {
                     "error":{
                       "code":"","message":"An error has occurred."
                     }
                   }
PowerBIErrorInfo : 
ResponseDate     : Mon, 29 Apr 2019 12:39:13 GMT
RequestMethod    : POST
RequestUri       : https://api.powerbi.com/v1.0/myorg/groups
InvocationInfo   : {New-PowerBIWorkspace}
Line             : New-PowerBIWorkspace -Name "New WS"
Position         : At line:1 char:1
                   + New-PowerBIWorkspace -Name "New WS"
                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace       :    at Microsoft.PowerBI.Api.V2.Groups.<CreateGroupWithHttpMessagesAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.<CreateGroupAsync>d__3.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.CreateGroup(IGroups operations, GroupCreationRequest requestParameters)
                      at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.NewWorkspaceAsUser(String workspaceName)
                      at Microsoft.PowerBI.Commands.Workspaces.NewPowerBIWorkspace.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()

Many thanks.

**Comment by KyronSr** [comment]
Just FYI, 2 years later and I get the same error with exactly the same stack trace.
