### ISSUE TITLE
Sequence contains more than one element exception when publishing dataset which overwrites an existing dataset that is used by 2 reports 

### ISSUE THREAD

**Issue by saviourofdp** [microsoft/powerbi-powershell#139]
If say, you publish a report, clone the report in the same workspace and then republish the original report:

```ps
$FilePath = "example.pbix"
$WorkspaceId = "..."
$report = New-PowerBIReport -Path $FilePath -WorkspaceId $WorkspaceId -ConflictAction CreateOrOverwrite
Copy-PowerBIReport -WorkspaceId $WorkspaceId -Id $report.Id -Name "example 2"
New-PowerBIReport -Path $FilePath -WorkspaceId $WorkspaceId -ConflictAction
```
I get an error from the second publish
<pre>Exception        : System.InvalidOperationException: Sequence contains more than one element
                      at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
                      at  Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, 
                   String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
                      at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
InnerException   : False
Message          : Sequence contains more than one element
StackTrace       :    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
                      at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, 
                   String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
                      at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
HelpLink         : 
Source           : System.Linq
ErrorDetails     : 
ErrorCategory    : WriteError: (Microsoft.PowerBI.C\u2026ts.NewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], 
                   InvalidOperationException
InvocationInfo   : System.Management.Automation.InvocationInfo</pre>

Presumably from the [`return import.Reports.Single();`](https://github.com/microsoft/powerbi-powershell/blob/5302228cc00da2911719fd670a3323d84afccb50/src/Common/Common.Api/Reports/ReportsClient.cs#L206) at the end of `PostReportForWorkspace` because there are now 2 reports in the collection

```cs
public Report PostReportForWorkspace(Guid workspaceId, string reportName, string filePath, ImportConflictHandlerModeEnum nameConflict, int timeout)
        {
            var importId = this.PostImportForWorkspace(workspaceId, reportName, filePath, nameConflict);

            Nullable<DateTime> timeoutAt = null;
            if (timeout > 0)
            {
                timeoutAt = DateTime.Now.AddSeconds(timeout);
            }

            Import import = null;
            do
            {
                import = this.GetImportForWorkspace(workspaceId: workspaceId, importId: importId);

                if (import.ImportState != "Succeeded")
                {
                    if (timeoutAt != null && DateTime.Now > timeoutAt)
                    {
                        throw new TimeoutException();
                    }
                    else
                    {
                        System.Threading.Thread.Sleep(500);
                    }
                }

            } while (import.ImportState == "Publishing");

            if (import.ImportState != "Succeeded")
            {
                throw new ImportException(importId, reportName, import.ImportState);
            }

            return import.Reports.Single();
        }
```

**Comment by RuiRomano** [comment]
Any updates on this?

**Comment by cmantz** [comment]
Any updates? This is an issue for us too, we were trying to use this to update datasets programatically though Azure DevOps, but this is breaking our PowerShell deployment script.
