### ISSUE TITLE
unauthorised when calling Get-PowerBIActivityEvent as a Service Principal

### ISSUE THREAD

**Issue by o-o00o-o** [microsoft/powerbi-powershell#209]
We have a service principal setup on Azure and it is a member of the Power BI administrator group

![image](https://user-images.githubusercontent.com/13693159/74032129-23f95700-49ab-11ea-990d-b3ea5050a555.png)

``` powershell
$cred = Get-Credential
Connect-PowerBIServiceAccount -ServicePrincipal -Credential $cred -Tenant <directory guid>


Environment : Public
TenantId    :
ClientId    : *******30bb
Password    : ********


PS C:\WINDOWS\system32> Get-PowerBIActivityEvent -StartDateTime 2020-02-06T00:00:00 -EndDateTime 2020-02-06T23:59:59
Get-PowerBIActivityEvent : Operation returned an invalid status code 'Unauthorized'
At line:1 char:1
+ Get-PowerBIActivityEvent -StartDateTime 2020-02-06T00:00:00 -EndDateT ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...BIActivityEvent:GetPowerBIActivityEvent) [Get-PowerBIActivityEvent], HttpOperationE
   xception
    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Admin.GetPowerBIActivityEvent

PS C:\WINDOWS\system32>  Resolve-PowerBIError -Last


   HistoryId: 61


RequestId        : ******
Response         : Unauthorized (401): {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","para
                   meters":{},"details":[],"exceptionCulprit":1}}}
PowerBIErrorInfo :
ResponseDate     : Fri, 07 Feb 2020 13:15:50 GMT
RequestMethod    : GET
RequestUri       : https://api.powerbi.com/v1.0/myorg/admin/activityevents?startDateTime='2020-02-06T00:00:00'&endDateTime='2020-02-06T00:01:00'
InvocationInfo   : {Get-PowerBIActivityEvent}
Line             : Get-PowerBIActivityEvent -StartDateTime 2020-02-06T00:00:00 -EndDateTime 2020-02-06T00:01:00
Position         : At line:1 char:1
                   + Get-PowerBIActivityEvent -StartDateTime 2020-02-06T00:00:00 -EndDateT ...
                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace       :    at Microsoft.PowerBI.Api.V2.Admin.<GetActivityEventsWithHttpMessagesAsync>d__10.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.AdminExtensions.<GetActivityEventsAsync>d__11.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.AdminExtensions.GetActivityEvents(IAdmin operations, String startDateTime, String endDateTime,
                   String continuationToken, String filter)
                      at Microsoft.PowerBI.Common.Api.Admin.AdminClient.GetPowerBIActivityEvents(String startDateTime, String endDateTime,
                   String continuationToken, String filter)
                      at Microsoft.PowerBI.Commands.Admin.GetPowerBIActivityEvent.ExecuteCmdletHelper(String formattedStartDateTime, String
                   formattedEndDateTime)
                      at Microsoft.PowerBI.Commands.Admin.GetPowerBIActivityEvent.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
HistoryId        : 61
```

This does work if I log in with a normal (user) account that is in the same role. 

Are there any other permissions required? We have enabled Service Principals in the Tenant Admin area and I can't find any other documentation on this. 

We need this so we can automate downloading these logs without requiring MFA

**Comment by nerddtvg** [comment]
We had the same problem and unfortunately were pointed to this:
https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#considerations-and-limitations

>Service principal currently does not support any admin APIs.

These are simply not supported no matter the permissions you provide. Application Authentication is not supported for these endpoints.

I also found this Power BI Ideas post requesting this functionality. Please vote on it if you can: https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39641572-need-service-principle-support-for-admin-api
