### ISSUE TITLE
Restore-PowerBIWorkspace throws  Not Found (404)

### ISSUE THREAD

**Issue by SuryaBoja** [microsoft/powerbi-powershell#230]
Hi Team,

I tried below to restore the deleted workspace. whereas when I tried get-workspaces I do see those workspaces still in delete state. Below is what I used.

` _Get-PowerBIWorkspace -scope Organization -Deleted_`

**OutPut**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Id                    : 88888888-8888-8888-8888-888888888888
Name                  : testingPowerBIRestore
Type                  : Group
State                 : Deleted
IsReadOnly            : False
IsOrphaned            : False
IsOnDedicatedCapacity : False
CapacityId            :
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

` _ Restore-PowerBIWorkspace -Id "88888888-8888-8888-8888-888888888888" -RestoredName "testingPowerBIRestore" -AdminEmailAddress "********@********.onmicrosoft.com"_`

**OutPut**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING: Only preview workspaces are supported when -Scope Organization is specified
Restore-PowerBIWorkspace : Operation returned an invalid status code 'NotFound'
At line:1 char:1
+ Restore-PowerBIWorkspace -Id "88888888-8888-8888-8888-888888888888" - ...
+ 
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:RestorePowerBIWorkspace) [Restore-PowerBI
   Workspace], HttpOperationException
    + FullyQualifiedErrorId : Operation returned an invalid status code 'NotFound',Microsoft.PowerBI.Commands.Workspac
   es.RestorePowerBIWorkspace
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`_ Resolve-PowerBIError -Last_`

**OutPut**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RequestId        : ac0a32c8-46a9-4419-8694-922f5ff0f359
Response         : Not Found (404): {"error":{"code":"PowerBIEntityNotFound","pbi.error":{"code":"PowerBIEntityNotFound
                   ","parameters":{},"details":[],"exceptionCulprit":1}}}
PowerBIErrorInfo :
ResponseDate     : Wed, 03 Jun 2020 12:54:09 GMT
RequestMethod    : POST
RequestUri       : https://api.powerbi.com/v1.0/myorg/admin/groups/88888888-8888-8888-8888-888888888888/restore
InvocationInfo   : {Restore-PowerBIWorkspace}
Line             : Restore-PowerBIWorkspace -Id "88888888-8888-8888-8888-888888888888" -RestoredName "testingPowerBIRestore"
                   -AdminEmailAddress "********@********.onmicrosoft.com"
Position         : At line:1 char:1
                   + Restore-PowerBIWorkspace -Id "88888888-8888-8888-8888-888888888888" - ...
                   + 
StackTrace       :    at
                   Microsoft.PowerBI.Api.V2.Groups.<RestoreDeletedGroupAsAdminWithHttpMessagesAsync>d__21.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.<RestoreDeletedGroupAsAdminAsync>d__33.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.RestoreDeletedGroupAsAdmin(IGroups operations,
                   String groupId, GroupRestoreRequest groupRestoreRequest)
                      at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.RestoreDeletedWorkspaceAsAdmin(Guid
                   workspaceId, WorkspaceRestoreRequest restoreRequest)
                      at Microsoft.PowerBI.Commands.Workspaces.RestorePowerBIWorkspace.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
HistoryId        : 5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**_MicrosoftPowerBIMgmt version 1.0.840_**

Is here someone faced with the same issue? Please help me

**Comment by CattieCat** [comment]
Can you please provide the output from a recent repro? We need a recent RequestId to investigate.
