### ISSUE TITLE
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array

### ISSUE THREAD

**Issue by NGseb** [microsoft/powerbi-powershell#261]
i have upgraded to latest version, but i recevie the error : 
![image](https://user-images.githubusercontent.com/16684953/97594271-ce664e00-1a02-11eb-8784-ca0b0b89f12a.png)

`PS C:\> $allWS=Get-PowerBIWorkspace -Scope Organization -All 
Get-PowerBIWorkspace : Attempted to access an element as a type incompatible with the array.
At line:1 char:8
+ $allWS=Get-PowerBIWorkspace -Scope Organization -All
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspace], ArrayTypeMismatchException
    + FullyQualifiedErrorId : Attempted to access an element as a type incompatible with the array.,Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace`

**Comment by jayanth2830** [comment]
This sounds like an issue with NewtonsoftJSON dll version mismatch. Can you try running the commands from Powershell core?

**Comment by JTUoB** [comment]
Can we have this issue fixed? PowerShell Core doesn't work for the AzureAD module, which is required for automating Power BI access. I raised this issue on the Power BI forums here: https://community.powerbi.com/t5/Developer/PowerShell-AzureAD-cmdlets-incompatible-with/td-p/1684100, which shows how this is a breaking change with no workaround.

This affects several other cmdlets as well so very far reaching error.

**Comment by nickedase** [comment]
> Can we have this issue fixed? PowerShell Core doesn't work for the AzureAD module, which is required for automating Power BI access. I raised this issue on the Power BI forums here: https://community.powerbi.com/t5/Developer/PowerShell-AzureAD-cmdlets-incompatible-with/td-p/1684100, which shows how this is a breaking change with no workaround.
> 
> This affects several other cmdlets as well so very far reaching error.

Any news or workaround for this issue?

**Comment by NGseb** [comment]
I just downloaded the latest version  (1.0.974) and it is still not fixed for me !

**Comment by CattieCat** [comment]
We are not clear about what to fix since non of us can repro this issue
Following @jayanth2830 's direction
Please 
1) check your PS version $PSVersionTable
3) check which version of newtonsoft.json dll is loaded in your PS session when using MicrosoftPowerBIMgmt. It should load from MicrosoftPowerBIMgmt location for Windows PowerShell
Here's my working example
![image](https://user-images.githubusercontent.com/6728488/117506954-475adb00-af3b-11eb-9530-c9e11decfda3.png)

**Comment by JTUoB** [comment]
Did have a slightly older version of Newtonsoft.Json but updated the Power BI modules and still get the same issue. PS Version is 5.1 as usual - just to note as I said before this can't use PS Core as AzureAD module is not supported.

![image](https://user-images.githubusercontent.com/79577655/117639004-5cbe4800-b17b-11eb-9fca-725c8e87e1be.png)

**Comment by CattieCat** [comment]
I don't have much clue as version and location are exactly the same for us about Newtonsoft.Json. I'm going to follow up about this issue for more context.
In the mean time, can I know why you need to use Connect-AzureAD instead of Login-PowerBI? Cause we support PS Core.

**Comment by dvaco-dba** [comment]
I am having the same issue. It seems to be related to using VS Code. When I run [Newtonsoft.Json.JsonConvert].Module I get the below. This is not coming from Windows PowerShell as expected per the above comment. I'm using PS 5.1 in VS Code, not PS Core as there are issues with the MicrosoftPowerBIMgmt module in Core.

![image](https://user-images.githubusercontent.com/63610803/119683280-84ffa500-be11-11eb-8d68-f096e7ef7338.png)

**Comment by JTUoB** [comment]
> I don't have much clue as version and location are exactly the same for us about Newtonsoft.Json. I'm going to follow up about this issue for more context.
> In the mean time, can I know why you need to use Connect-AzureAD instead of Login-PowerBI? Cause we support PS Core.

I'm not using Connect-AzureAD for Power BI? We need to be able to access our Azure AD tenant however to be able to create and work with groups that provision access to Power BI workspaces.

**Comment by ozhug** [comment]
I have this issue in VScode as well 
When I run [Newtonsoft.Json.JsonConvert].Module in VS Code I get the below. This is not coming from Windows PowerShell as expected per the above comment.
gives me version 11 not 12

**Comment by MasterKuat** [comment]
Hi, same issue in a Azure automation context.
```
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
                      at System.Collections.Generic.List`1.Add(T item)
                      at Microsoft.PowerBI.Api.V2.PowerBIClient.Initialize()
                      at Microsoft.PowerBI.Api.V2.PowerBIClient..ctor(Uri baseUri, ServiceClientCredentials  credentials, HttpClientHandler rootHandler, DelegatingHandler[] handlers)
                      at Microsoft.PowerBI.Common.Api.PowerBIApiClient.CreateClient(IAuthenticationFactory authenticator, IPowerBIProfile profile, IPowerBILogger logger, IPowerBISettings settings, HttpClientHandler httpClientHandler)
                      at Microsoft.PowerBI.Common.Client.PowerBIClientFactory.CreateClient(IAuthenticationFactory                 authenticator, IPowerBIProfile profile, IPowerBILogger logger, IPowerBISettings settings)
                      at Microsoft.PowerBI.Common.Client.PowerBIClientCmdlet.CreateClient()
                      at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
                      at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
```
I ran this on a hybrid worker with latest module version : 1.2.1026
But seems Newtonsoft dll loaded by automation is version 13 and not 12 as specified in current version.

`[Newtonsoft.Json.JsonConvert].Module` gave : 
```
MDStreamVersion    : 131072
FullyQualifiedName : C:\Program Files\Microsoft Monitoring                      Agent\Agent\AzureAutomation\7.3.1209.0\HybridAgent\Newtonsoft.Json.13.dll
ModuleVersionId    : f7499511-9334-484f-b6db-6825be2eac0d
MetadataToken      : 1
ScopeName          : Newtonsoft.Json.dll
Name               : Newtonsoft.Json.13.dll
Assembly           : Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CustomAttributes   : {}
ModuleHandle       : System.ModuleHandle
```

Is it possible to update version dependency of Newtonsoft ?

Thanks

**Comment by CattieCat** [comment]
For all incompatible array element issue related to Newtonsoft, please
consider switching to PowerShell Core or using
https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/invoke-powerbirestmethod?view=powerbi-ps
 + https://docs.microsoft.com/en-us/rest/api/power-bi/.

We have already tested updating version dependency of Newtonsoft (a lot of
work to release), and tested with Azure Automation team, yet it didn't
help, and in Azure automation we were loaded Newtonsoft 6 each time.
Given this issue doesn't repro with PowerShell Core and there's plan for
Azure Automation to support PowerShell Core next year, we decided not to
put more limited resources on this issue.

**Comment by MasterKuat** [comment]
Hi @CattieCat,
Thanks for your answer.
I replace Get-PowerBIWorkpace by Invoke-PowerBIRestMethod and it's ok.
For the record, I do it this way : 
```
    if ($WorkspaceID) {
        $url = "groups?`$filter=id eq '$WorkspaceID' and type eq 'Workspace'"
    } elseif ($WorkspaceName) {
        $url = "groups?`$filter=name eq '$WorkspaceName' and type eq 'Workspace'"
    } else {
        throw "Specify an Id or a worskapce Name"
    }
....
    $ResObj  = Invoke-PowerBIRestMethod -Url $url -Method GET | ConvertFrom-Json
    if ($ResObj.'@odata.count' -eq 1) {
        $WorkspaceID = $ResObj.value.Id 
    } else {
        throw "Workspace not found"
    }
```

**Comment by MWPatterson2000** [comment]
Seeing this is over a year old is there an ETA on a resolution for this?

**Comment by JTUoB** [comment]
Is there going to be a fix for this issue? This is preventing us using a large amount of available cmdlets that require retrieving IDs from Azure (e.g. we can't use Add-PowerBIWorkspaceUser for security groups). The AzureAD module still isn't supported in PowerShell Core so we still can't manage our Power BI tenant effectively.

**Comment by lajuyu** [comment]
We had a Microsoft tech that help us with this issue and provided us with the code to run it in Azure Automation.  This runs in PowerShell 5.1 HybridWorker.  Make sure your Hybrid Worker has all the modules for PowerBI.  Hope this helps.

if ($($env:computerName) -eq "Client") {"Runbook running on Azure Client sandbox"} else {"Runbook running on " + $env:computerName}

Write-Output "Parent runbook"
[Newtonsoft.Json.JsonConvert].Module
$cred = Get-AutomationPSCredential -Name 'TheName'
#POWERBI MODULE SECTION
# PowerShell background Job for PowerBI module to avoid modules incompatibility
Write-Warning "Starting PowerShell background for PowerBI module"
 $job = Start-Job -ScriptBlock { 
        Param($jobResults)

    Write-Output "Importing Orchestrator AssetManagement Cmdlets module"
    Import-Module Orchestrator.AssetManagement.Cmdlets 

    #Start of your code
    Connect-PowerBIServiceAccount -Credential $using:Cred

    Get-PowerBIWorkspace -Scope Organization -All

    #End of your code

    Write-Output "Background job Newtonsoft Version check 1"
    [Newtonsoft.Json.JsonConvert].module
} -ArgumentList (,$Results) 

Write-Output "Waiting for Job to finish"
Wait-Job $job
Write-Output "Retrieving Job output"
Receive-Job -ID $job.id -keep

**Comment by kchirravuri** [comment]
This worked for me as of March 2024 on a VM that is on Azure. 

Install-Module -Name AzureAD
Install-Module -Name MicrosoftPowerBIMgmt
Install-Module -Name Newtonsoft.Json
Login-PowerBI

Get-PowerBIActivityEvent -StartDateTime 2024-03-26T00:00:00 -EndDateTime 2024-03-26T01:00:00

$PSVersionTable - 5.1.20348.2227
Windows Server 2022 Datacenter Azure Edition

Same exact thing did not work on my laptop.
