### ISSUE TITLE
InternalServerError when running Get-PowerBIWorkspace

### ISSUE THREAD

**Issue by b-per** [microsoft/powerbi-powershell#297]
Hi!

Since this morning, I get the following error when running `Get-PowerBIWorkspace` (and many other commands):

```
Get-PowerBIWorkspace : Operation returned an invalid status code 'InternalServerError'
At line:1 char:1
+ Get-PowerBIWorkspace
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspace], HttpOperationException
    + FullyQualifiedErrorId : Operation returned an invalid status code 'InternalServerError',Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace
```

Here is the result of `Resolve-PowerBIError -Last`:
```
RequestId        : d8a0848e-b0c5-4f4d-b8c3-417897614ccd
Response         : Internal Server Error (500): {"Message":"An error has occurred."}
PowerBIErrorInfo :
ResponseDate     : Mon, 31 May 2021 03:58:45 GMT
RequestMethod    : GET
RequestUri       : https://api.powerbi.com/v1.0/myorg/groups?$top=100
InvocationInfo   : {Get-PowerBIWorkspace}
Line             : Get-PowerBIWorkspace
Position         : At line:1 char:1
                   + Get-PowerBIWorkspace
                   + ~~~~~~~~~~~~~~~~~~~~
StackTrace       :    at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
                      at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
                      at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
                      at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
```

**Comment by CattieCat** [comment]
I tried to look for the logs from server side but 1) the log is incomplete with this request ID 2) there's no error info. 
Can you please share a most recent repro if it still occurs for you?

**Comment by b-per** [comment]
Hi!
The Cmdlet was failing for a few hours but started to work again after, without any change from my side. I'll close this one.
