### ISSUE TITLE
Get-PowerBIDashboard doesn't recognise logon

### ISSUE THREAD

**Issue by DRG2407** [microsoft/powerbi-powershell#356]
Connect-PowerBIServiceAccount
Get-PowerBIDashboard -Scope Organization
Get-PowerBIDashboard : Login first with Login-PowerBIServiceAccount
At line:1 char:1
+ Get-PowerBIDashboard -Scope Organization
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PowerBIDashboard], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.PowerBI.Commands.Reports.GetPowerBIDashboard

PS C:\Users\admdaniel.goodman> resolve-powerbierror -last

   HistoryId: 21

Message        : Login first with Login-PowerBIServiceAccount
StackTrace     :    at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.AssertProfileExists()
                    at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.BeginProcessing()
                    at Microsoft.PowerBI.Commands.Reports.GetPowerBIDashboard.BeginProcessing()
                    at System.Management.Automation.Cmdlet.DoBeginProcessing()
                    at System.Management.Automation.CommandProcessorBase.DoBegin()
Exception      : System.Exception
InvocationInfo : {Get-PowerBIDashboard}
Line           : Get-PowerBIDashboard -Scope Organization
Position       : At line:1 char:1
                 + Get-PowerBIDashboard -Scope Organization
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 21

**Comment by jayanth2830** [comment]
@DRG2407 Do you get an error when running Connect-PowerBIServiceAccount? If not, does the login command output the tenant ID and user name?

**Comment by zhunipingan** [comment]
the same issue, do you have any solution
