### ISSUE TITLE
Uninformative 'Failed' State in New-PowerBIReport ImportException

### ISSUE THREAD

**Issue by WongResearch** [microsoft/powerbi-powershell#406]
Hello,

I am reaching out to report an issue encountered with the New-PowerBIReport cmdlet in the Power BI PowerShell module. The cmdlet fails to upload a report to a Power BI workspace, resulting in an ImportException that provides little to no useful information for diagnosing the root cause. 

Error Logs:

Exception        : Microsoft.PowerBI.Common.Api.Reports.ImportException: The import was not successful for import ID 
                    '00000000-0000-000-0000-00000000', report name 'name.pbix'. The import 
                    state was 'Failed'.
                       at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, 
                    String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
                       at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
                       at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
InnerException   : False
Message          : The import was not successful for import ID '00000000-0000-000-0000-00000000', report name 
                    'name.pbix'. The import state was 'Failed'.
StackTrace       :    at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, 
                   String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32 timeout)
                       at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
                       at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
Source           : Microsoft.PowerBI.Common.Api

The message indicating the import state as 'Failed' provides no meaningful insight or actionable information to help identify or troubleshoot the underlying issue. This lack of detail is particularly challenging, as it hinders our ability to diagnose and resolve the problem effectively.

**Comment by dsantunes** [comment]
Did you ever find a solution for this?

Getting the same, with no changes to reports or scripts:

> TargetSite     : Microsoft.PowerBI.Common.Api.Reports.Report PostReportForWorkspace(System.Guid, System.String, System.String, Microsoft.PowerBI.Common.Api.Reports.ImportConflictHandlerModeEnum, Int32)
Message        : The import was not successful for import ID 'f9bc0937-c752-481a-88b8-9a4f22c4fc6b', report name 'Portfolio Level.pbix'. The import state was 'Failed'.
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.PowerBI.Common.Api
HResult        : -2146233088
StackTrace     :    at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.PostReportForWorkspace(Guid workspaceId, String reportName, String filePath, ImportConflictHandlerModeEnum nameConflict, Int32
                 timeout)
                    at Microsoft.PowerBI.Commands.Reports.NewPowerBIReport.ExecuteCmdlet()
                    at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
