### ISSUE TITLE
Permissions needed for Service Principal

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/powerbi-powershell#51]
Is there a guide on how to create an Azure AD registered app (aka Service Principal) that has permissions to use these powershell commands?  

I created an 'App Registration' in our Azure Active Directory.

I had our global admin grant it the 'Read and write all content in tenant' and 'View all content in tenant' permissions

I login successfully:
```
$tenantId = '<redacted>'
$applicationId = '<redacted>'
$key = '<redacted>'

$secureKey = ConvertTo-Securestring -String $key -AsPlainText -Force
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $applicationId,$secureKey

Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -Tenant $tenantId

Environment : Public
TenantId    : 
ClientId    : <redacted>
Password    : ********
```

But I get an unauthorized error from any of the commands:
```
PS> Get-PowerBIReport
Get-PowerBIReport : Operation returned an invalid status code 'Unauthorized'
```

**Comment by CodeCyclone** [comment]
You need to call with -Scope Organization which will cause the cmdlet to call the Admin API for getting reports - https://docs.microsoft.com/en-us/rest/api/power-bi/admin/reports_getreportsasadmin.
Only the Admin APIs support Azure AD Application Only authentication currently.

If you run into an issue, call Resolve-PowerBIError -Last, this will give you more detail why the Power BI service rejected the call and allows us to research it further.

Thank you for raising the issue on needing a guide, I will get one created out at https://docs.microsoft.com/en-us/powershell/power-bi/overview?view=powerbi-ps. It sounds like you have the correct permissions assigned to your AAD application for calling the Admin APIs.

**Comment by RobCannon** [comment]
I tried 
```
Get-PowerBIGroup $groupName -Scope Organization
```
and got the same error.  Here are the results of Resolve-PowerBIError:
```



   HistoryId: 14


RequestId        : 1402bbdc-d056-4e73-b794-3b7acfde92da
Response         : Unauthorized (401): {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerB
                   INotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
PowerBIErrorInfo :
ResponseDate     : Fri, 13 Jul 2018 14:06:26 GMT
RequestMethod    : GET
RequestUri       : https://api.powerbi.com/v1.0/myorg/admin/groups?$expand=users&$filter=tolower(name) eq
                   'engage-test'
InvocationInfo   : {Get-PowerBIWorkspace}
Line             : Get-PowerBIGroup -Name $groupName -Scope Organization
Position         : At line:1 char:1
                   + Get-PowerBIGroup -Name $groupName -Scope Organization
                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace       :    at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsAsAdminWithHttpMessagesAsync>d__13.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
                   task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsAdminAsync>d__17.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
                   task)
                      at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroupsAsAdmin(IGroups operations, String
                   expand, String filter, Nullable`1 top, Nullable`1 skip)
                      at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspacesAsAdmin(String
                   expand, String filter, Nullable`1 top, Nullable`1 skip)
                      at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
HistoryId        : 14
```

**Comment by CodeCyclone** [comment]
After further investigation, it appears the APIs regressed in this functionality and a fix is being worked on.

The issue isn't in the PowerShell cmdlets, they are correctly authenticating to the service so the turn around will be slower for a fix but it is being worked on. I will keep the issue open for tracking.

**Comment by mthierba** [comment]
@CodeCyclone Would you be able to share any updates on this? I am still consistently getting a 401 when trying to use the new /admin endpoints with application-level permissions (authenticating with a Service Principal). You pointed out that this is not an issue related to the PS modules - Is there any other repo where this could be followed more directly?

**Comment by Rosablanche** [comment]
@CodeCyclone Any update on that one ? I still hit authorization error as soon as I ad dthe -scope switch.

Any known workaround ?

**Comment by raix** [comment]
@CodeCyclone I'm sorry about poking like this - but we are well into a project everything working until we try using the service principle - it's kinda critical for out project - and viewing the progress on this issue we are considering other options. Any Eta on this issue?

**Comment by raix** [comment]
@CodeCyclone I just saw @RobCannon question about automating - Can you confirm that a service principle login should allow creating dataset + table, update table column definition, remove all rows and push row data?

**Comment by CodeCyclone** [comment]
Update for Connect-PowerBIServiceAccount was released in https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt/1.0.342.

I will keep this issue open till Service Principal is supported

**Comment by demetrioi** [comment]
Hi folks,

Still not working

![image](https://user-images.githubusercontent.com/10916434/50484029-684eb100-09bc-11e9-8d5d-5c1334f283ab.png)

`cls
#region code
$key = '******************'
$applicationId = '******************'
$tenantId = '******************'
#endregion code


$secureKey = ConvertTo-Securestring -String $key -AsPlainText -Force
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $applicationId,$secureKey

Connect-PowerBIServiceAccount -Credential $credential -Tenant $tenantId

Get-PowerBIReport -Scope Organization
`

version: C:\Program Files\WindowsPowerShell\Modules\MicrosoftPowerBIMgmt\1.0.342

**Comment by giarbi** [comment]
same issue

**Comment by naman27101985** [comment]
@RobCannon @demetrioi  : I am also getting same issue as you mentioned. I have spent a lot of effort fixing this but seems not to work. Did you find anything on this?

**Comment by RobCannon** [comment]
I gave up and went with another solution.

**Comment by demetrioi** [comment]
Hi @RobCannon wich other solution? Login-PowerBI still not woking with Azure Application App

**Comment by RobCannon** [comment]
An AWS solution.  Another team is working on it, so I don't have the details.

**Comment by allanmoller** [comment]
Damm just spend 2 hours trying to figure this out :-( seems like auth using SPNs is not working still. Any update?

**Comment by mthierba** [comment]
This has now been announced: https://powerbi.microsoft.com/en-us/blog/use-power-bi-api-with-service-principal-preview/

>  available by end of week  in Public Preview.

**Comment by demetrioi** [comment]
> This has now been announced: https://powerbi.microsoft.com/en-us/blog/use-power-bi-api-with-service-principal-preview/
> 
> > available by end of week  in Public Preview.

Hi folks,

The command still not working with App Credentials. Is there a ETA for this feature?

Regards,

Demetrio Silva

**Comment by fmms** [comment]
I have been trying this today with version 1.0.487.

It is not working. However, i do not have access to the Power BI admin portal. Maybe all issues posted here recently are because Service Principal access has to be enabled in the tenant.

See step 3 in https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal .

Can we verify whether it is a general permission error or the above setting?

regards

**Comment by vchauhangit** [comment]
I have followed all steps mentioned here https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal 
to access the Power BI Rest API through service app token.

1. Create an app with app permission (https://analysis.windows.net/powerbi/api/Tenant.ReadWrite.Al)
2. Login to Power BI (https://app.powerbi.com) and change Tenant setttings to Allow service principals to use Power BI APIs for the entire organization.

But when try to access use the service app token gives error:
-For Rest API  https://api.powerbi.com/v1.0/myorg/dashboards: {
    "Message": "API is not accessible for application"
}

-For Rest API https://api.powerbi.com/v1.0/myorg/admin/dashboards: {
    "error": {
        "code": "PowerBINotAuthorizedException",
        "pbi.error": {
            "code": "PowerBINotAuthorizedException",
            "parameters": {},
            "details": [],
            "exceptionCulprit": 1
        }
    }
}

Any help will be highly appreciated.

Thanks

**Comment by cfosund** [comment]
The Admin Power BI REST API does only work with an Global Administrator or Power BI Service Administrator in addition to Service Principal with the Application permission Tenant.Read or Tenant.ReadWrite. 

This needs to change asap.. 🤦‍♂️ Please help voting this idea up:
 https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39641572-need-service-principle-support-for-admin-api

**Comment by noahsdonaldson** [comment]
Hey cfosund,

Can you clarify that if you created an app registration (SP) and gave it the tenant read all permissions you still have to grant it Power BI Admin rights?  I just want to make sure that works because I have to ask another group to grant those rights and it seems odd that I would grant a Service Principal rights to Power BI Admin?

**Comment by andstein85** [comment]
I've noticed that with service principles and the power Bi api, you have to explicitly specify the workspace where your report(s)/dataset(s)/Table(s) are.

sooooo this doesn't work:
Get-PowerBIReport

but this will:
$workspace = Get-PowerBIworkspace
Get-PowerBIReport -WorkspaceId $workspace.Id 

I ran into this issue when trying to manipulate datasets and tables where this code wouldn't work when logging in with a service princple:
$dataset = Get-PowerBIDataset -Name "some-dataset-name"
$tablename = "Some-table-name"
Remove-PowerBIRow -DataSetId $dataset.Id -TableName $tablename
Add-PowerBIRow -DataSetId $dataset.Id -TableName $tablename -Rows ($report | ConvertTo-Json | ConvertFrom-Json)
-->don't ask about the convertto-json|convertfrom-json...there is a bug in the json processor in powershell core 7.

But adding the workspace to the parameters fixed it:
$workspace = Get-PowerBIworkspace
$dataset = Get-PowerBIDataset -WorkspaceId $workspace.Id -Name "some-dataset-name"
$tablename = "Some-table-name"
Remove-PowerBIRow -WorkspaceId $workspace.Id -DataSetId $dataset.Id -TableName $tablename
Add-PowerBIRow -WorkspaceId $workspace.Id -DataSetId $dataset.Id -TableName $tablename -Rows ($report | ConvertTo-Json | ConvertFrom-Json)

now if i could just figure out why remove-powerbirow and add-powerbirow cmdlets work locally but not in an azure function app..... anyway, you're welcome.

**Comment by agvago** [comment]
Hi guys!

According with this [documentation](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication)  we should be able to run some admins commands (check limitations). Has anyone had success on it? I followed this document and still getting Unauthorized! It can't be so hard, but I can't figured out!

**Comment by athioune** [comment]
Hello ! 

I have the same problem too and I still can't figured it out :(
Does someone solve the problem ?

Thank you !!

**Comment by agvago** [comment]
Hi! I solved the issue following this [documentation](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication).

**Comment by zhunipingan** [comment]
@tcc-sejohnson Hi, thanks for your sharing. But we can only read data from PowerBI, cannot update or add data to PowerBI through service principle? I plan to use service principle to upload new .pbix file to the powerBi workspace, but meett the 'unauthorized' error. Can we achieve uploading data through the API.
