### ISSUE TITLE
Export-PowerBIReport Is not working as admin

### ISSUE THREAD

**Issue by Weatwagon** [Microsoft/powerbi-powershell#65]
I'm running Export-PowerBIReport as global admin and I'm receiving an 'Unauthorized' error (full error below) for reports in workspaces I am not assigned or other user's personal workspaces. I can list all the reports in all the personal workspaces of other people though. We are in the middle of the transition process to GCC from the public tenant, it would be nice to export all of our user's content from the public tenant before we lose access. 

RequestId        : cc691c42-e5fa-4919-976f-846d8a1acf7c
Response         : Unauthorized (401): {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
PowerBIErrorInfo :
ResponseDate     : Thu, 09 Aug 2018 07:13:34 GMT
RequestMethod    : GET
RequestUri       : https://api.powerbi.com/v1.0/myorg/reports/46590729-0131-46a5-b702-bde21ed9033e/Export
InvocationInfo   : {Export-PowerBIReport}
Line             : Get-PowerBIReport  -WorkspaceId 'df5e1412-b279-4955-988e-6917af3d02ac' -Scope Organization | %{Export-PowerBIReport -Id $_.id -OutFile D:\ner.pbix }
Position         : At line:1 char:96
                   + ... rganization | %{Export-PowerBIReport -Id $_.id -OutFile D:\ner.pbix }
                   +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace       :    at Microsoft.PowerBI.Api.V2.Reports.<ExportReportWithHttpMessagesAsync>d__9.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.ReportsExtensions.<ExportReportAsync>d__29.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.PowerBI.Api.V2.ReportsExtensions.ExportReport(IReports operations, String reportKey)
                      at Microsoft.PowerBI.Common.Api.Reports.ReportsClient.ExportReport(Guid reportId, Nullable`1 workspaceId)
                      at Microsoft.PowerBI.Commands.Reports.ExportPowerBIReport.ExecuteCmdlet()
                      at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
HistoryId        : 173

**Comment by hongju** [comment]
I got error too.
Export-PowerBIReport : Operation returned an invalid status code 'Unauthorized'

**Comment by mthierba** [comment]
@Weatwagon The [Export Report](https://docs.microsoft.com/rest/api/power-bi/reports/exportreport) operation is not one of the new [Admin operations](https://docs.microsoft.com/rest/api/power-bi/admin), hence whilst you can enumerate all reports in your workspace as a global admin, you can only export them as a user that has explicit access to all the workspaces and with an access token for the `Report.ReadWrite.All` or `Report.Read.All` scopes (these are set in your AAD application).

**Comment by CodeCyclone** [comment]
That is correct, we are considering creating an export for admin operation for the API but currently it only works when the calling user is assigned to the workspace.

**Comment by sqlchick** [comment]
Thanks for clarifying on the difference between the Export- cmdlet from the other Admin operations. Very helpful! Initially I was thinking that being able to reach into other users 'My Workspace' to back up content would be useful (particularly if we discover users are delivering important content via sharing from their workspace vs. utilizing an app workspace). Upon reflection, that would make a Power BI Admin suddenly have very far-reaching permissions, and the ability to see all data across the org, so I can see the need for a separate role that allows such elevated permissions.

**Comment by gregarican** [comment]
Would this scenario be similar to what I'm running into? I have granted a service principal admin-level access to a Power BI Pro workspace. Using the REST API I can list the workspace's reports, but when I try to export a specific report I am running into an HTTP 401 - Unauthorized error. Example below.

`POST https://api.powerbi.com/v1.0/myorg/groups/{group_id}/reports/{report_id}/ExportTo


HTTP/1.1 401 Unauthorized
Content-Length: 153
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: deny
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: RequestId
request-redirected: true
home-cluster-uri: https://wabi-us-central-a-primary-redirect.analysis.windows.net/
RequestId: 80d737b7-d156-4852-b520-14d067bbebe3
Date: Fri, 19 Jun 2020 13:40:53 GMT

{"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}`

**Comment by SAgnihotri200895** [comment]
do we have any update on this ?Is it still not possible to export reports as admin ?
